from django.urls import path
from .viewsfetchsql import (
    PaysView, RegionView, VilleView, ImportanceGeoView, TypeSiteView, LotTechniqueView,
    FamilleEquipementView, GroupeEquipementView, BatimentView, NiveauView, TypeEspaceView,
    EspaceSQLView, SiteSQLView, PrestataireView, CriticiteEquipementView, NbrSiteView,
    EquipementSQLView, StatutNCView, HistoriqueNCView, NonConformiteView, RondeView,
    RondeCommentairesView, RondeEventView, RondeParametreView, RondeReleveView,
    TypeRealisationView, UniteMesureView, DonneeMesureView, InterventionView,
    InterventionAttachementView, InterventionIntervenantsView, InterventionPrestataireView,
    PlanificationView, DetailPlanificationView, FrequenceView, DetailPlanificationInterventionView,
    UserView, UserAffecView, MarcheView,CriticiteNCView,ActionIntegrationView,StatutActionIntegrationView
)

urlpatterns = [
    path('pays/', PaysView.as_view(), name='pays'),
    path('region/', RegionView.as_view(), name='region'),
    path('ville/', VilleView.as_view(), name='ville'),
    path('importance-geo/', ImportanceGeoView.as_view(), name='importance-geo'),
    path('type-site/', TypeSiteView.as_view(), name='type-site'),
    path('lot-technique/', LotTechniqueView.as_view(), name='lot-technique'),
    path('famille-equipement/', FamilleEquipementView.as_view(), name='famille-equipement'),
    path('groupe-equipement/', GroupeEquipementView.as_view(), name='groupe-equipement'),
    path('batiment/', BatimentView.as_view(), name='batiment'),
    path('niveau/', NiveauView.as_view(), name='niveau'),
    path('type-espace/', TypeEspaceView.as_view(), name='type-espace'),
    path('espace-sql/', EspaceSQLView.as_view(), name='espace-sql'),
    path('site-sql/', SiteSQLView.as_view(), name='site-sql'),
    path('prestataire/', PrestataireView.as_view(), name='prestataire'),
    path('criticite-equipement/', CriticiteEquipementView.as_view(), name='criticite-equipement'),
    path('nbr-site/', NbrSiteView.as_view(), name='nbr-site'),
    path('equipement-sql/', EquipementSQLView.as_view(), name='equipement-sql'),
    path('statut-nc/', StatutNCView.as_view(), name='statut-nc'),
    path('historique-nc/', HistoriqueNCView.as_view(), name='historique-nc'),
    path('non-conformite/', NonConformiteView.as_view(), name='non-conformite'),
    path('criticite-nc/', CriticiteNCView.as_view(), name='non-conformite'),
    path('ronde/', RondeView.as_view(), name='ronde'),
    path('ronde-commentaires/', RondeCommentairesView.as_view(), name='ronde-commentaires'),
    path('ronde-event/', RondeEventView.as_view(), name='ronde-event'),
    path('ronde-parametre/', RondeParametreView.as_view(), name='ronde-parametre'),
    path('ronde-releve/', RondeReleveView.as_view(), name='ronde-releve'),
    path('type-realisation/', TypeRealisationView.as_view(), name='type-realisation'),
    path('unite-mesure/', UniteMesureView.as_view(), name='unite-mesure'),
    path('donnee-mesure/', DonneeMesureView.as_view(), name='donnee-mesure'),
    path('intervention/', InterventionView.as_view(), name='intervention'),
    path('intervention-attachement/', InterventionAttachementView.as_view(), name='intervention-attachement'),
    path('intervention-intervenants/', InterventionIntervenantsView.as_view(), name='intervention-intervenants'),
    path('intervention-prestataire/', InterventionPrestataireView.as_view(), name='intervention-prestataire'),
    path('planification/', PlanificationView.as_view(), name='planification'),
    path('detail-planification/', DetailPlanificationView.as_view(), name='detail-planification'),
    path('frequence/', FrequenceView.as_view(), name='frequence'),
    path('detail-planification-intervention/', DetailPlanificationInterventionView.as_view(), name='detail-planification-intervention'),
    path('user/', UserView.as_view(), name='user'),
    path('user-affec/', UserAffecView.as_view(), name='user-affec'),
    path('marche/', MarcheView.as_view(), name='marche'),
    path('action/', ActionIntegrationView.as_view(), name='marche'),
    path('statut-action/', StatutActionIntegrationView.as_view(), name='marche'),
]